version: '3.8'

services: 
  vueapp: 
    container_name: web 
    build: 
      context: . 
      dockerfile: Dockerfile.vueapp 
    ports: 
      - 8080:80 
    networks: 
      - frontend_network 
    depends_on: 
      - database 
      - api 

  api: 
    container_name: api 
    build: 
      context: . 
      dockerfile: Dockerfile.api 
    ports: 
      - 8000:80 
    networks: 
      - frontend_network 
      - backend_network 
    depends_on: 
      - database 

  database: 
    container_name: db 
    image: postgres:alpine 
    environment: 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes: 
      - db_data:/var/lib/postgresql/data 
    networks: 
      - backend_network 

networks: 
  frontend_network: 
    driver: bridge 

  backend_network: 
    driver: bridge 

volumes: 
  db_data:
