# API
FROM python:3.10.10-slim-buster

WORKDIR /app

RUN pip install --upgrade pip
RUN apt-get update && apt-get install libzbar0 -y

COPY ./requirements.txt .
COPY ./api api
COPY ./scripts api

RUN pip install -r requirements.txt

EXPOSE 80

# Start FastAPI server
CMD ["sh", "-c", "cd api && uvicorn main:app --host 0.0.0.0 --port 80 --reload --workers 1"]