# API
FROM python:3.11-slim

WORKDIR /app

RUN pip install --upgrade pip
RUN apt-get update && apt-get install libzbar0 -y

COPY ./requirements.txt .
COPY ./api api
COPY ./scripts api
COPY ./.env api

RUN pip install -r requirements.txt

EXPOSE 80

# Start FastAPI server
CMD ["sh", "-c", "cd api && uvicorn main:app --host 0.0.0.0 --port 80 --workers 6"]